source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/block.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/plsmodel.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/innerW.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/initM1.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/Utils.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/step1.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/wscheme.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/step2.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/step3.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/step4.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/step5.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/pathCoeffs.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/totEffects.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/dgrho.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/rSquared.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/gof.R")
#
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/plsExtpm.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/plsExtboot.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/plsExtplot.R")
source("C:/Users/Jorge Mendes/OneDrive - NOVAIMS/ISEGI/PLS-SEM paper/GitHub/package/functions/plsExtcheck.R")
###########################################################################################################################
